### ISSUE TITLE
Documentation needs to mention that all Secrets are synced to the daemons database

### ISSUE THREAD

**Issue by martialblog** [Icinga/icinga-kubernetes#112]
I think it is **very** important to let users know that all Secrets the daemon can get its hands on are stored into its database.

This has a lot of security implications. K8S Cluster admins might put a lot of work into securing API access to Secrets, backups of secrets and so on. All while the monitoring team siphon Secrets from the cluster and granting different access.

The documentation needs to highlight this very clearly.

Might even be an idea to think about not syncing Secrets by default. I don't see how they are relevant for monitoring the state of a workload. A workload might not start because a Secret is missing in the cluster. But that can be detectable without storing said Secret in the daemon's database

**Comment by lippserd** [comment]
Thank you for the issue. Secret and config map data are no longer synchronized.
