### ISSUE TITLE
Pod icinga-stack-icinga-kubernetes-6467d68799-rzznc failing to start

### ISSUE THREAD

**Issue by conorgriffin1995** [Icinga/icinga-kubernetes#121]
**App Version: 0.3.0**
**Installation Type: Helm**

**Problem:**
Kubernetes pod stuck in warning state and constantly restarting:

![image](https://github.com/user-attachments/assets/fb0b15dd-bfbb-4646-8eef-8cd1f1854b33)

**Error in container logs:**
I0905 12:11:51.938266       1 driver.go:43] "Can't connect to database. Retrying" logger="database" error="dial tcp 10.0.70.170:3306: connect: connection refused"
I0905 12:13:14.934067       1 driver.go:48] "Reconnected to database" logger="database"
I0905 12:13:14.934966       1 main.go:86] "Importing schema" logger="database"
F0905 12:00:44.304514       1 main.go:278] can't retry: can't perform "INSERT INTO `service` (`namespace`, `cluster_ip`, `external_traffic_policy`, `uid`, `created`, `type`, `yaml`, `internal_traffic_policy`, `health_check_node_port`, `publish_not_ready_addresses`, `allocate_load_balancer_node_ports`, `load_balancer_class`, `uuid`, `name`, `session_affinity`, `ip_families`, `cluster_ips`, `ip_family_policy`, `resource_version`, `external_ips`, `external_name`) VALUES (:namespace, :cluster_ip, :external_traffic_policy, :uid, :created, :type, :yaml, :internal_traffic_policy, :health_check_node_port, :publish_not_ready_addresses, :allocate_load_balancer_node_ports, :load_balancer_class, :uuid, :name, :session_affinity, :ip_families, :cluster_ips, :ip_family_policy, :resource_version, :external_ips, :external_name) ON DUPLICATE KEY UPDATE `namespace` = VALUES(`namespace`), `cluster_ip` = VALUES(`cluster_ip`), `external_traffic_policy` = VALUES(`external_traffic_policy`), `uid` = VALUES(`uid`), `created` = VALUES(`created`), `type` = VALUES(`type`), `yaml` = VALUES(`yaml`), `internal_traffic_policy` = VALUES(`internal_traffic_policy`), `health_check_node_port` = VALUES(`health_check_node_port`), `publish_not_ready_addresses` = VALUES(`publish_not_ready_addresses`), `allocate_load_balancer_node_ports` = VALUES(`allocate_load_balancer_node_ports`), `load_balancer_class` = VALUES(`load_balancer_class`), `uuid` = VALUES(`uuid`), `name` = VALUES(`name`), `session_affinity` = VALUES(`session_affinity`), `ip_families` = VALUES(`ip_families`), `cluster_ips` = VALUES(`cluster_ips`), `ip_family_policy` = VALUES(`ip_family_policy`), `resource_version` = VALUES(`resource_version`), `external_ips` = VALUES(`external_ips`), `external_name` = VALUES(`external_name`)": Error 1265 (01000): Data truncated for column 'type' at row 1

**Error in pod icinga-stack-kubernetes-database-0 container logs:**
2024-09-05 12:05:51 143 [Warning] Aborted connection 143 to db: 'kubernetes' user: 'kubernetes' host: '10.2.18.8' (Got an error reading communication packets)

**Helm install command:**
`envsubst < $SCRIPT_DIR/icinga-helm.yml | helm upgrade   --install icinga-stack $SCRIPT_DIR/helm    --namespace "$target_namespace"   -f -
`

**icinga-kubernetes values:**

```
icinga-kubernetes:
  enabled: true

  image:
    repository: icinga/icinga-kubernetes
    tag: edge
    pullPolicy: Always

  rbac:
    create: true

  serviceAccount:
    create: true
```

**Comment by lippserd** [comment]
Hi @conorgriffin1995,

This has been fixed. Please see Icinga/helm-charts#61.

Best regards,
Eric
