### ISSUE TITLE
icinga-kubernetes[865034]: I0930 10:55:28.464897  865034 driver.go:43] "Can't connect to database. Retrying" logger="database" error="context canceled"

### ISSUE THREAD

**Issue by lokidaibel** [Icinga/icinga-kubernetes#138]
Fresh install on RHEL 9 Host.

Followed all instructions, now running at the very first start into this:

Sep 30 10:55:28 lim-vt21.lvrintern.lvr.de icinga-kubernetes[865034]: I0930 10:55:28.464897  865034 driver.go:43] "Can't connect to database. Retrying" logger="database" error="context canceled"

Any Idee ?

**Comment by lokidaibel** [comment]
Sep 30 10:55:28 <my-host-name> systemd[1]: Starting Icinga for Kubernetes...
Sep 30 10:55:28 <my-host-name> icinga-kubernetes[865034]: I0930 10:55:28.088023  865034 database.go:285] "Connecting to database" logger="database"
Sep 30 10:55:28 <my-host-name> icinga-kubernetes[865034]: I0930 10:55:28.464886  865034 driver.go:43] "Can't connect to database. Retrying" logger="database" error="context canceled"
Sep 30 10:55:28 <my-host-name> icinga-kubernetes[865034]: I0930 10:55:28.464889  865034 driver.go:43] "Can't connect to database. Retrying" logger="database" error="context canceled"
Sep 30 10:55:28 <my-host-name> icinga-kubernetes[865034]: I0930 10:55:28.464892  865034 driver.go:43] "Can't connect to database. Retrying" logger="database" error="context canceled"
Sep 30 10:55:28 <my-host-name> icinga-kubernetes[865034]: I0930 10:55:28.464893  865034 driver.go:43] "Can't connect to database. Retrying" logger="database" error="context canceled"
Sep 30 10:55:28 <my-host-name> icinga-kubernetes[865034]: [invalid connection]
Sep 30 10:55:28 <my-host-name> icinga-kubernetes[865034]: I0930 10:55:28.464897  865034 driver.go:43] "Can't connect to database. Retrying" logger="database" error="context canceled"

**Comment by lippserd** [comment]
Hi @lokidaibel,

Looks like you're running version `0.1.0`.  Version `0.2.0` has been released last week and is also available for RHEL 9.

Best regards,
Eric

**Comment by lokidaibel** [comment]
Used your Repo to install  it. Maybe update Repos ;D ?

**Comment by lippserd** [comment]
> Used one of your binary Repo to install it.

Which repo did you use?

> Any ETA when there will be a 0.2 release avaialable to install ?

packages.icinga.com have them since Friday last week.

Any chance your using a mirror, reposync, whatever?

**Comment by lokidaibel** [comment]
My fault. Lokal Repo out of Sync ;D

**Comment by lippserd** [comment]
> My fault. Lokal Repo out of Sync ;D

No worries. Glad it was that easy 😆.
