### ISSUE TITLE
Can it will be added and watched in different environments?

### ISSUE THREAD

**Issue by firatalkis** [Icinga/icinga-kubernetes#143]
Hi,

We have 4 environment as prod, preprod, test and prod-2. If it's on your agenda, I am sorry:) 

Can icinga-kubernetes, will be monitoring more then one of the kubernetes environment?

kind, regards
Fırat.

**Comment by lippserd** [comment]
Hi @firatalkis,

We already have this on our roadmap: #95.

Best regards,
Eric
