### ISSUE TITLE
Missing Icinga Kubernetes Web documentation

### ISSUE THREAD

**Issue by VadymKultenkoDarth** [Icinga/icinga-kubernetes#62]
I tried to open a link to [Icinga Kubernetes Web](https://icinga.com/docs/icinga-kubernetes-web) and it doesn't work. can you please confirm if the url is correct?

**Comment by AlessandroTaufer** [comment]
Seems like all the "docs related" links in the README file are not working.
- [https://icinga.com/docs/icinga-kubernetes](https://icinga.com/docs/icinga-kubernetes)
- [https://icinga.com/docs/icinga-kubernetes-web](https://icinga.com/docs/icinga-kubernetes-web)

**Comment by lippserd** [comment]
Hi,

The links have been fixed.

Best regards,
Eric
