### ISSUE TITLE
[ERROR] Out of range value for column 'restart_count'

### ISSUE THREAD

**Issue by razvanmac95** [Icinga/icinga-kubernetes#65]
Hi,

The icinga-kubernetes container stopped with the following error message:

`can't retry: can't perform "INSERT INTO `container` (`id`, `state_details`, `state`, `started`, `restart_count`, `image`, `cpu_limits`, `pod_id`, `name`, `memory_requests`, `memory_limits`, `ready`, `cpu_requests`) VALUES (:id, :state_details, :state, :started, :restart_count, :image, :cpu_limits, :pod_id, :name, :memory_requests, :memory_limits, :ready, :cpu_requests) ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `state_details` = VALUES(`state_details`), `state` = VALUES(`state`), `started` = VALUES(`started`), `restart_count` = VALUES(`restart_count`), `image` = VALUES(`image`), `cpu_limits` = VALUES(`cpu_limits`), `pod_id` = VALUES(`pod_id`), `name` = VALUES(`name`), `memory_requests` = VALUES(`memory_requests`), `memory_limits` = VALUES(`memory_limits`), `ready` = VALUES(`ready`), `cpu_requests` = VALUES(`cpu_requests`)": Error 1264 (22003): Out of range value for column 'restart_count' at row 19`

**Comment by lippserd** [comment]
Hi @razvanmac95,

As a temporary fix, please run the following statement in the database:

`ALTER TABLE container MODIFY COLUMN restart_count int unsigned NOT NULL;`

Best regards,
Eric

**Comment by razvanmac95** [comment]
Hi @lippserd 

That worked, I'll do it this way until the next release.

Thanks,
Razvan

**Comment by razvanmac95** [comment]
Indeed, good question. Until now, I've used the default MySQL setup for the rest of the Icinga applications. I didn't consider stopping the binlog since I didn't have any problems with the rest. Everything is okay now, thank you.

**Comment by lippserd** [comment]
Fixed by 4e3ab1bc8899934676ef376e2b3cf39aed0bdae5.
