### ISSUE TITLE
The database is very large

### ISSUE THREAD

**Issue by razvanmac95** [Icinga/icinga-kubernetes#67]
Hi,

After running the icinga-kubernetes container for 2 days, the MySQL database for this module reached 85Gb for a small cluster.

Thanks,
Razvan

**Comment by lippserd** [comment]
Hi @razvanmac95,

Can you please run the following query in the Icinga for Kubernetes database:

```sql
SELECT
  TABLE_NAME AS `Table`,
  ROUND((DATA_LENGTH + INDEX_LENGTH) / 1024 / 1024) AS `Size (MB)`
FROM
  information_schema.TABLES
WHERE
  TABLE_SCHEMA = DATABASE()
ORDER BY
  (DATA_LENGTH + INDEX_LENGTH)
DESC;
```

I think it's because we don't truncate container logs.

Best regards,
Eric

**Comment by razvanmac95** [comment]
I did a cleanup because we ran out of space on the server, and it stopped the whole setup. But I've started the container again and will run this after the volume increases again.

**Comment by razvanmac95** [comment]
`mysql> SELECT TABLE_NAME AS `Table`, ROUND((DATA_LENGTH + INDEX_LENGTH) / 1024 / 1024) AS `Size (MB)` FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE() ORDER BY (DATA_LENGTH + INDEX_LENGTH) DESC;
+-----------------------------+-----------+
| Table                       | Size (MB) |
+-----------------------------+-----------+
| container_log               |       275 |
| data                        |        40 |
| secret_data                 |         8 |
| secret                      |         6 |
| event                       |         0 |
| pod_volume                  |         0 |
| replica_set_label           |         0 |
| container                   |         0 |
| pod_condition               |         0 |
| label                       |         0 |
| pod_label                   |         0 |
| pod                         |         0 |
| replica_set_owner           |         0 |
| replica_set                 |         0 |
| kubernetes_schema           |         0 |
| pod_pvc                     |         0 |
| pod_metrics                 |         0 |
| pvc                         |         0 |
| pod_owner                   |         0 |
| replica_set_condition       |         0 |
| persistent_volume_claim_ref |         0 |
| persistent_volume           |         0 |
| node_volume                 |         0 |
| pvc_condition               |         0 |
| pvc_label                   |         0 |
| namespace_label             |         0 |
| secret_label                |         0 |
| selector                    |         0 |
| service                     |         0 |
| service_condition           |         0 |
| service_label               |         0 |
| service_port                |         0 |
| service_selector            |         0 |
| stateful_set                |         0 |
| stateful_set_condition      |         0 |
| stateful_set_label          |         0 |
| endpoint_slice_label        |         0 |
| config_map_data             |         0 |
| config_map_label            |         0 |
| container_device            |         0 |
| container_mount             |         0 |
| cron_job                    |         0 |
| cron_job_label              |         0 |
| daemon_set                  |         0 |
| daemon_set_condition        |         0 |
| daemon_set_label            |         0 |
| deployment                  |         0 |
| deployment_condition        |         0 |
| deployment_label            |         0 |
| endpoint                    |         0 |
| endpoint_slice              |         0 |
| node_label                  |         0 |
| endpoint_target_ref         |         0 |
| ingress                     |         0 |
| ingress_backend_resource    |         0 |
| ingress_backend_service     |         0 |
| ingress_rule                |         0 |
| ingress_tls                 |         0 |
| job                         |         0 |
| job_condition               |         0 |
| job_label                   |         0 |
| namespace                   |         0 |
| namespace_condition         |         0 |
| config_map                  |         0 |
| node                        |         0 |
| node_condition              |         0 |
+-----------------------------+-----------+
66 rows in set (0.12 sec)

> du -hs icinga_icingak8s-mysql
3.6G	icinga_icingak8s-mysql`

**Comment by lippserd** [comment]
Thanks. Can you please also run this statement?

```sql
SELECT COUNT(*) FROM container_log log LEFT JOIN container ON container.id = log.container_id WHERE container.id IS NULL;
```

**Comment by razvanmac95** [comment]
`mysql> SELECT COUNT(*) FROM container_log log LEFT JOIN container ON container.id = log.container_id WHERE container.id IS NULL;
+----------+
| COUNT(*) |
+----------+
|        0 |
+----------+
1 row in set (0.00 sec)`

**Comment by razvanmac95** [comment]
It seems that the large size is due to the binlog files.

**Comment by lippserd** [comment]
> It seems that the large size is due to the binlog files.

Which binlog files?

**Comment by razvanmac95** [comment]
/var/lib/docker/volumes/icinga_icingak8s-mysql/_data

du -hs *
4.0K	auto.cnf
3.0M	binlog.000001
1.1G	binlog.000002
1.1G	binlog.000003
1.1G	binlog.000004
1.1G	binlog.000005
1.1G	binlog.000006
1.1G	binlog.000007
1.1G	binlog.000008
1.1G	binlog.000009
1.1G	binlog.000010
1.1G	binlog.000011
1.1G	binlog.000012
1.1G	binlog.000013
1.1G	binlog.000014
1.1G	binlog.000015
1.1G	binlog.000016
1.1G	binlog.000017
699M	binlog.000018
4.0K	binlog.index

**Comment by lippserd** [comment]
I see. But why do you have binary logging enabled for the Kubernetes database?

**Comment by razvanmac95** [comment]
Indeed, good question. Until now, I've used the default MySQL setup for the rest of the Icinga applications. I didn't consider stopping the binlog since I didn't have any problems with the rest. Everything is okay now, thank you.

**Comment by lippserd** [comment]
Glad that helped. Though this has nothing to do with this issue, somebody else reported [memory issues](https://github.com/Icinga/icinga-kubernetes/issues/64#issuecomment-2015315446). If you find anything suspicious as well, please open a new issue.

**Comment by lippserd** [comment]
And by the way, I'm quite sure binary logs are only needed for replicated setups. For some operations MySQL creates binlogs on its own but that is nothing that can be configured. I'm wondering why this hasn't been an issue before in your setup. IDO/Icinga DB is also a write heavy component for example.

**Comment by lippserd** [comment]
> Glad that helped. Though this has nothing to do with this issue, somebody else reported [memory issues](https://github.com/Icinga/icinga-kubernetes/issues/64#issuecomment-2015315446). If you find anything suspicious as well, please open a new issue.

Oh, I think it's you ;).

**Comment by prasadkris** [comment]
@lippserd Greetings, I have the same issue, but in my case, the container logs are occupying the space. Is there a way to disable the container logs collection as I don't really need it? Or any suggestions to fix this? Thank you. 🙏🏻 

```
mysql> SELECT 
    ->     TABLE_NAME AS `Table`, 
    ->     ROUND((DATA_LENGTH + INDEX_LENGTH) / 1024 / 1024, 2) AS `Size (MB)`
    -> FROM 
    ->     information_schema.TABLES 
    -> WHERE 
    ->     TABLE_SCHEMA = DATABASE() 
    -> ORDER BY 
    ->     (DATA_LENGTH + INDEX_LENGTH) DESC;
+-----------------------------+-----------+
| Table                       | Size (MB) |
+-----------------------------+-----------+
| container_log               |  19635.05 |
| data                        |     54.55 |
| event                       |     52.02 |
| label                       |     22.55 |
| endpoint                    |     10.05 |
| pod_condition               |      6.05 |
| pod_volume                  |      5.06 |
| container                   |      4.17 |
| pod_label                   |      3.05 |
| replica_set_label           |      2.22 |
| job_label                   |      2.20 |
| job                         |      1.31 |
| replica_set                 |      1.25 |
| pod                         |      1.25 |
| replica_set_owner           |      1.23 |
| pod_owner                   |      1.08 |
| node_label                  |      0.34 |
| job_condition               |      0.28 |
| endpoint_slice_label        |      0.28 |
| node_condition              |      0.23 |
| service_label               |      0.20 |
| service                     |      0.17 |
| deployment_condition        |      0.17 |
| secret                      |      0.16 |
| config_map_label            |      0.16 |
| service_selector            |      0.14 |
| deployment_label            |      0.14 |
| config_map_data             |      0.14 |
| endpoint_slice              |      0.13 |
| config_map                  |      0.13 |
| secret_data                 |      0.13 |
| pvc_label                   |      0.13 |
| secret_label                |      0.11 |
| endpoint_target_ref         |      0.09 |
| persistent_volume           |      0.09 |
| deployment                  |      0.09 |
| pvc                         |      0.08 |
| service_port                |      0.08 |
| persistent_volume_claim_ref |      0.08 |
| stateful_set_label          |      0.06 |
| pod_pvc                     |      0.05 |
| stateful_set                |      0.05 |
| selector                    |      0.05 |
| kubernetes_schema           |      0.03 |
| replica_set_condition       |      0.02 |
| ingress_tls                 |      0.02 |
| namespace_label             |      0.02 |
| container_device            |      0.02 |
| namespace_condition         |      0.02 |
| daemon_set                  |      0.02 |
| ingress_backend_resource    |      0.02 |
| daemon_set_label            |      0.02 |
| cron_job_label              |      0.02 |
| ingress                     |      0.02 |
| namespace                   |      0.02 |
| cron_job                    |      0.02 |
| ingress_backend_service     |      0.02 |
| pod_metrics                 |      0.02 |
| container_mount             |      0.02 |
| node                        |      0.02 |
| daemon_set_condition        |      0.02 |
| ingress_rule                |      0.02 |
| pvc_condition               |      0.02 |
| service_condition           |      0.02 |
| node_volume                 |      0.02 |
| stateful_set_condition      |      0.02 |
+-----------------------------+-----------+
66 rows in set (0.00 sec)
```

**Comment by lippserd** [comment]
Container logs are truncated from version 0.2.0. The latest images or snapshot packages already contain the fix.
