### ISSUE TITLE
Wrong Schema File Location in Documentation

### ISSUE THREAD

**Issue by tectumopticum** [Icinga/icinga-kubernetes#71]
Documentation should be corrected:
I installed  icinga-kubernetes-0.1.0-1.x86_64.rpm and icinga-kubernetes-web-0.1.0-1.noarch.rpm from the repo successfully.
According to https://icinga.com/docs/icinga-kubernetes/latest/doc/02-Installation/SLES/ the schema.sql should be located in /usr/share/kubernetes/schema/mysql/schema.sql but it is located in /usr/share/icinga-kubernetes/schema/mysql/schema.sql

If you call
```
mariadb < /usr/share/icinga-kubernetes/schema/mysql/schema.sql
```
you'll get an error "ERROR 1046 (3D000) at line 1: No database selected"
Maybe a first line "USE kubernetes;" should be added

**Comment by lippserd** [comment]
@tectumopticum Thanks for the report. We'll fix the location of the schema file but we can't just add `USE kubernetes` to the schema file as you could name the database whatever you want.

**Comment by lippserd** [comment]
@Jan-Schuppik Please fix the documentation.
