### ISSUE TITLE
`INSERT INTO node_volume` fails with `Error 1406 (22001): Data too long for column 'name'`

### ISSUE THREAD

**Issue by jayintheoffice** [Icinga/icinga-kubernetes#91]
### Affected Chart

icinga-stack

### Please describe your problem

I'm attempting to install to my Azure Kubernetes Service cluster as per:

helm install icingaks \
  --namespace icinga \
  --set icinga2.config.ticket_salt.value=PASSWORD \
  --set icingaweb2.auth.admin_password.value=PASSWORD \
  --set global.api.users.director.password.value=PASSWORD \
  --set global.api.users.icingaweb.password.value=PASSWORD \
  --set global.databases.director.username.value=director_user \
  --set global.databases.director.password.value=PASSWORD \
  --set global.databases.icingaweb2.username.value=icingaweb2_user \
  --set global.databases.icingaweb2.password.value=PASSWORD \
  --set global.databases.icingadb.username.value=icingadb_user \
  --set global.databases.icingadb.password.value=PASSWORD \
  --set global.databases.kubernetes.username.value=kubernetes_user \
  --set global.databases.kubernetes.password.value=PASSWORD \
icinga/icinga-stack

(where each 'PASSWORD' is a unique 11-character alphanumeric string)

Most pods appear to spin up OK with the exception these two: 

icinga-kubernetes

I0507 06:16:00.618931       1 database.go:285] "Connecting to database" logger="database"
F0507 06:16:01.004741       1 main.go:204] can't retry: can't perform "INSERT INTO `node_volume` (`name`, `device_path`, `mounted`, `node_id`) VALUES (:name, :device_path, :mounted, :node_id) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `device_path` = VALUES(`device_path`), `mounted` = VALUES(`mounted`), `node_id` = VALUES(`node_id`)": Error 1406 (22001): Data too long for column 'name' at row 1

icinga-stack-kubernetes-database

2024-05-07  7:10:43 483 [Warning] Aborted connection 483 to db: 'kubernetes' user: 'kubernetes_user' host: '10.2.12.28' (Got an error reading communication packets)

I have an nginx ingress service which appears to be working fine.

**Comment by lippserd** [comment]
refs #69
